//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStockAccept
    {
        public int Id { get; set; }
        public int AppUserId { get; set; }
        public int ProductId { get; set; }
        public string Barcode { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
